version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: garden_weather_controller
      POSTGRES_PASSWORD: garden_weather_controller_password
      POSTGRES_DB: garden_weather_controller

  garden-weather-controller:
    image: garden-weather-controller
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=garden_weather_controller
      - DB_PASSWORD=garden_weather_controller_password
      - DB_NAME=garden_weather_controller
      - DB_PORT=5432

